create table team (
    id   int generated by default as identity primary key,
    name varchar(100) not null
);

create table role (
    id   int generated by default as identity primary key,
    name varchar(50) not null
);

create table player (
    id      int generated by default as identity primary key,
    name    varchar(150) not null,
    team_id int not null references team (id),
    role_id int not null references role (id)
);

create table game (
    id       int generated by default as identity primary key,
    team1_id int not null references team (id),
    team2_id int not null references team (id)
);

create table result (
    id                     int generated by default as identity primary key,
    game_id                int not null unique references game (id),
    winning_team_id        int not null references team (id),
    losing_team_id         int not null references team (id),
    player_of_the_match_id int not null references player (id)
);
